name: intrepion-jwt-rest-client-web
region: sfo
static_sites:
  - build_command: npm run build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: intrepion/intrepion-intrepion-jwt-rest-client-web-typescript-react-typescript
    name: jwt-rest-client-web
    routes:
      - path: /
    source_dir: /
